### ISSUE TITLE
Feature: use trigram in fts5 - text searching

### ISSUE THREAD

**Issue by savage13** [zeldamods/radar#22]
Changing the FTS5 tokenizer from `unicode61` to `trigram` would allow for better object visibility and improved searching.

Positives:
- Improves object visibility and object finding 
   - e.g. `dragon` finds all objects with a substring of dragon: `DragonDropItemTarget` is one example
- Searching is more responsive as shorter strings match earlier
   - Minimum characters is 3 for a substring
- Preset searches continue to work 

Negatives:
- Increases the size of the `map.db` database (225 MB to 575MB)
- Increases build time for the database

See: https://www.sqlite.org/fts5.html#the_experimental_trigram_tokenizer

**Comment by leoetlino** [comment]
Sounds awesome. The increased space usage is not really an issue, and the longer build time is probably not a problem either; we don't really rebuild the database that often ;)

We need to make sure exact matches continue to work, though. (And update the in-app search help if necessary)

**Comment by savage13** [comment]
There may be some searchs that may confuse people:
- `shock arrow NOT enemy` (current)
- `shock arrow NOT actor: enemy` or `shock arrow NOT ^enemy` (new)


- `frog` (current) only results in Hot-Footed Frogs
- `frog NOT FldObj` (new) only results in Hot-Footed Frogs
   - `FldObj_SecretBaseFrogStatue_A_01` are the offering plates going into the Yiga Hideout


- `rupee NOT Chest` (current) 
- `rupee NOT Chest` (new) returns the above plus `Blupee`
   - a `Blupee` is an `Animal_RupeeRabbit_A`

Many of these can be resolved by specifying either extra or more specific search terms.

I think the immediate results as you type is worthwhile.
