### ISSUE TITLE
new parser breaks column filters on integers and bools

### ISSUE THREAD

**Issue by savage13** [zeldamods/radar#24]
- `hard: 0` or `hard: 1`  these both return no results.
-  `onehit:`, `lastboss:`, `no_rankup:`, `scale:`, `bonus:`, `fieldarea:`, `lotm:` - These are the same

Words less than 3 characters look like they are ignored so the columns with integer and boolean appear to be ignored or I have not found a way to access their values using a column-filter.

Possible solutions:
- Revert to previous tokenizer (unicode61: default)
- Identify a solution that allows for using the new tokenizer (or changing the values in the integer/boolean columns)
- Create a modified tokenizer (this looks like a lot of work and might be a source of bugs)
   - It would operate like trigram but would add the short text sequences as well

Sorry about this   :(

**Comment by leoetlino** [comment]
Yeah modifying sqlite probably won't be a very enjoyable experience.

Can we create two FTS tables, one that uses the unicode61 tokenizer and the other using the trigram tokenizer? And then query both tables and merge+deduplicate the results?

**Comment by leoetlino** [comment]
Actually, that probably isn't a good idea because it means adding e.g. `hard:0` would suddenly cause partial matches to stop working.

**Comment by savage13** [comment]
At the cost of more complex code/computation, could we look for and remove strings in the query like `lotm:\s*([0-1])`.  If they exist we add additional where clauses to the query.

**Comment by leoetlino** [comment]
That would probably only work for simple queries. Something like "(hard:0 AND Bokoblin) OR (hard:1 AND Lizalfos)" would be pretty difficult to transform.

**Comment by savage13** [comment]
I think reverting this change and thinking more about this would be appropriate right now.

**Comment by leoetlino** [comment]
Sounds like a plan.
