### ISSUE TITLE
Add region filter for object search

### ISSUE THREAD

**Issue by savage13** [zeldamods/radar#5]
Add region filtering for object search (based on tower regions)

I was able to parse the beco file in javascript and query the Area Number for each object.   Below is an image of the tower regions based on number.  It should match, color-for-color, what is currently on the objmap.

What would be the best way to implement a filter on the Tower region.  Possible options:

- Determine position and region using the exisiting getCurrentAreaNum() -- seems like overkill as the full Beco data would need to kept in memory
- Determine region using a database table representation of the Beco data -- tried this and it is somewhat slow and results in complex sql queries
- Predetermine the regions and add them as a column in the object table -- I like this the best as it integrates with the existing full text search and searching on columns

![tower_regions](https://user-images.githubusercontent.com/126514/129724092-0b1ddd67-e96a-4bea-aa3a-a50f76e492d6.png)

**Comment by leoetlino** [comment]
> Predetermine the regions and add them as a column in the object table -- I like this the best as it integrates with the existing full text search and searching on columns

Yeah, I agree with this.

**Comment by savage13** [comment]
While writing the getCurrentAreaNum() function, I noticed the function at https://zeldamods.org/wiki/Beco clamps the row between `0` and `num_rows-2`.  I would have expected `num_rows-1` as it is 0-indexed.  Data exists on the final row, but the clamp() at `-2` does not allow it access.  

Have I missed something?  I see that it is directly from the `official, mostly unreversed function`.

**Comment by leoetlino** [comment]
Yeah, the -2 is definitely what Nintendo does. :man_shrugging: 
 
![image](https://user-images.githubusercontent.com/4209061/129748060-a463ef29-2186-4ff7-adfa-2c7c84ce0bc2.png)

**Comment by savage13** [comment]
This is complete.
